# Generated by Django 4.2.5 on 2023-09-20 08:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('View_Api', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='Users',
        ),
    ]
