# Generated by Django 4.2.5 on 2023-09-20 08:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('View_Api', '0002_rename_user_users'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Users',
            new_name='User',
        ),
    ]
